### ISSUE TITLE
Permission settings?

### ISSUE THREAD

**Issue by MostHated** [matthewhall/fsui#1]
Hey there,
    I am getting the following error:

```shell
[debug] [2020-05-16T22:19:36.290Z] May 16, 2020 5:19:36 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: No matching allow statements

[debug] [2020-05-16T22:19:36.290Z] May 16, 2020 5:19:36 PM io.gapi.emulators.netty.HttpHandler$1 onError
INFO: Exception when handling request: PERMISSION_DENIED: No matching allow statements
```

I do apologize, I am new to Firebase/Firestore. Is there something I need to change in my demo project for this to work? I was just messing around with some of the samples provided from the Firebase github, so it's all default. The current one I was using is:

```tf
service cloud.firestore {
  match /databases/{database}/documents {
    match /{doc=**} {
      allow read, write;
    }
  }
}

```

---
Edit:
Looks like I had to add ```rules_version = '2';``` to their demos for it to work. 

It is able to access the data now, but it looks like the display may not be outputting properly, though?

The data displays down at the bottom, but with all the space in the middle it feels like there is supposed to be something there?
![](https://i.imgur.com/ObBMFhN.png)

Thanks,
-MH

**Comment by matthewhall** [comment]
Hi,

This project is still in development at the moment and I'm still actively building most features in my own time. As such, the version here on GitHub isn't working correctly and shouldn't be relied upon.

I hope to have something ready soon so please check back at a later date. At some point I'll push this as an NPM package with some proper documentation.

It's good to know there's interest in the project as well.

Cheers.

**Comment by MostHated** [comment]
No worries. At the moment I was just looking for a way to easily get some feedback on some things I was testing. This was my first go at using Firebase, so even though it is not complete it was still super helpful being able to quickly see the data that was saved in there, so it's a win as far as I am concerned, lol. I appreciate that you took the time to make it. 👍

**Comment by MostHated** [comment]
I pulled some of the changes you made. It looks and so far has been working great. Nice job, man. 👍

**Comment by matthewhall** [comment]
Hi.

I've now release a very basic first version to NPM. You can find it here: https://www.npmjs.com/package/fseui.

Cheers.
